config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "client#user_login"
  
  # master
  namespace :master do
    get "index"
    get "get_cheers"
    get "stanby"
    get "get_status"
    get "get_message"
    get "fever"
    get "get_users"
  end

  # client
  namespace :client do
    get "index"
    get "user_login"
    post "user_create"
    post "post_cheer"
  end
  
  # manage
  namespace :manage do
    post "start_playing"
    post "stop_playing"
    get "index"
    get "delete_users"
    get "delete_players"
    get "result"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cheer.rb
class Cheer < ApplicationRecord
  belongs_to :player
  belongs_to :user
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :cheers
  has_many :users, through: :cheers
  
  def self.now_playing_player
    find_by(:play_flg => 1)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cheers
  has_many :players, through: :cheers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/client_controller.rb
class ClientController < ApplicationController

  layout "client_application"

  def index
    unless session[:user_id]
      redirect_to :action => "user_login"
    end
  end
  
  def user_login
    if session[:user_id]
      redirect_to :action => "index"
    end
  end
      
  def user_create
    user = User.new
    user.name = params[:user_name]
    user.save
    
    session[:user_name] = user.name
    session[:user_id] = user.id
    
    redirect_to :action => "index"
  end

  def post_cheer
    player = Player.now_playing_player
    
    if player
      cheer = player.cheers.build
      cheer.user_id = session[:user_id]
      cheer.save
    end
  end
  
end

app/controllers/manage_controller.rb
class ManageController < ApplicationController
  def index
    @now_playing_player = Player.now_playing_player
  end

  def stop_playing
    Player.update(:play_flg => 0)

    redirect_to :action => "index"
  end

  def start_playing
    player = Player.new
    player.name = params[:name]
    player.play_flg = 1
    player.save

    redirect_to :action => "index"
  end
  
  def delete_users
  	User.all.each do | user |
  	  user.cheers.delete_all
  	  user.delete
  	end
  	
  	redirect_to :action => "index"
  end
  
  def delete_players
    Player.all.each do | player |
      player.cheers.delete_all
      player.delete
    end
  	
  	redirect_to :action => "index"
  
  end
  
  def result
    players = Player.all
    pleyers_name = players.collect{|player| player.name; }
    player_got_wakarimi = players.collect{|player| player.cheers.count; }
    # グラフ（チャート）を作成 
    @each_dj_chart = LazyHighCharts::HighChart.new("graph") do |c|
      c.title(text: "DJ個別結果")
      c.xAxis(categories: pleyers_name, title: {text: "出演DJ"})
      c.yAxis(title: {text: "獲得分かりみ数"})
      c.series(name: "獲得分かりみ数", data: player_got_wakarimi )
      c.chart(type: "column")
    end
    
    cheer_data = []
    hours = []
    event_start_time = Time.parse("2018/01/27 14:15:00")
    (event_start_time.to_i..Time.parse("2018/01/27 20:15:00").to_i).step(60*15).each do | idx |
      idx2 = Time.at(idx).ago(60*15)
    	cheer_data << Cheer.where(:created_at => idx2..Time.at(idx)).count
    	hours << idx.strftime("%H：%M")
    end
    
    # グラフ（チャート）を作成 
    @event_chart = LazyHighCharts::HighChart.new("graph") do |c|
      c.xAxis(categories: hours, title: {text: "時間"})
      c.title(text: "イベント総合結果")
      c.yAxis(title: {text: "獲得分かりみ数"})
      c.series(name: "獲得分かりみ数", data: cheer_data )
      
    end
  end

end

app/controllers/master_controller.rb
class MasterController < ApplicationController

  layout "master_application"

  def index
    @now_playing_player = Player.now_playing_player
    @cheers = @now_playing_player.cheers if @now_playing_player
    @users = User.all
    
  end
  
  def fever
    @now_playing_player = Player.now_playing_player
    @cheers = @now_playing_player.cheers if @now_playing_player
  end

  def get_cheers
    @cheers = Player.now_playing_player.cheers
    @users = User.all.sort{|a, b| b.cheers.count <=> a.cheers.count }
    
    to = Time.now
    from = to.ago(5)
    cheer_step_a_minute = @cheers.where(created_at: from..to).size
    
    from = to.ago(60)
    twitter_access
    tweets = @client.search("#ガチ恋ガーデン #わかりみ since:#{from.strftime('%Y-%m-%d_%H:%M:%m')}_JST until:#{to.strftime('%Y-%m-%d_%H:%M:%m')}_JST", result_type: "recent", exclude: "retweets", since_id: nil)
    
    player = Player.now_playing_player
    
    tweets.each do |tw|
      if player
        cheer = player.cheers.build
        cheer.user_id = User.first.id
        cheer.save
      end
    end
    
    if cheer_step_a_minute >= 2
      step_status = 1
    elsif cheer_step_a_minute == 0
      step_status = -1
    elsif cheer_step_a_minute == 1
      step_status = 0
    end

    status = {counter: @cheers.count, step_status: step_status}
    render :json => status and return
  end

  def stanby
  end
 
  def get_status
    now_playing_player = Player.now_playing_player
    if now_playing_player
      status = {status: "playing"}
      render :json => status and return
    else
      status = {status: "stanby"}
      render :json => status and return
    end
  end

private
  def twitter_access
    @client = Twitter::REST::Client.new do |config|
    config.consumer_key = "EBHKOkhqFc87vYeC3qBuwiUY8"
    config.consumer_secret = "VQXctGMKGWA914TlobhrQlfL8Vq1oW1caRiVEuqEjc0nHO6BZ3"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manage_helper.rb
module ManageHelper
end

app/views/application/index.html.erb
<script type="text/javascript">

$(function(){
var count = 1;

function get_status(){
    $.ajax({
      url: '/get_status',
      type: 'GET',
      success: function(json){
        if(json.status == "stanby"){
          window.location.href = "/stanby";
        } else if(json.status == "fever"){
          window.location.href = "/fever";
        }
      }
    });
}

function get_message(){
    $.ajax({
      url: '/get_message',
      type: 'GET'
    });
}


function refresh(){
    get_status();
/*
    if(count % 10 == 0){
      get_message();
    }
*/
    $.ajax({
        url: '/get_cheers',
        type: 'GET'
    });
    setTimeout(refresh, 1000);
    count++;
}

function rect() {
    $('#fever_time').animate({
        marginTop: '-=80px'
    }, 300).animate({
        marginTop: '+=80px'
    }, 300);
    setInterval('rect()', 1000); //アニメーションを繰り返す間隔
}

  refresh();
  setInterval(rect, 1000); //アニメーションを実行
 

    
});

</script>




<% if @now_playing_user %>
<p class="wakarimi_count heart">
<span id="counter">
<%= render :partial =>  "count" %>
</span>
</p>

<!--
<div id="message">
<%= render :partial => "message" %>
</div>
-->
<div class="marquee">
	<p>現在　<%= @now_playing_user.player_name %>　がプレイ中です。</p>
</div>
<% else %>
<br /><br />
<div class="marquee">
  <p>現在準備中です。プレイ開始まで少々お待ちください。</p>
</div>
<% end %>

app/views/application/master.html.erb
<script type="text/javascript">

$(function(){
var count = 1;

function get_status(){
    $.ajax({
      url: '/master/get_status',
      type: 'GET',
      success: function(json){
        if(json.status == "stanby"){
          window.location.href = "/master/stanby";
        } else if(json.status == "fever"){
          window.location.href = "/master/fever";
        }
      }
    });
}


function refresh(){
    get_status();
    
    $.ajax({
        url: '/master/get_cheers',
        type: 'GET'
    });
    setTimeout(refresh, 3000);
    count++;
}

function rect() {
    $('#fever_time').animate({
        marginTop: '-=80px'
    }, 300).animate({
        marginTop: '+=80px'
    }, 300);
    setInterval('rect()', 1000); //アニメーションを繰り返す間隔
}

  refresh();
  setInterval(rect, 1000); //アニメーションを実行
 

    
});

</script>




<% if @now_playing_player %>
<p class="wakarimi_count heart">
<span id="counter">
<%= render :partial =>  "count" %>
</span>
</p>


<div id="users">
<%= render :partial => "users" %>
</div>

<div class="marquee">
	<p>現在　<%= @now_playing_player.name %>　がプレイ中です。</p>
</div>
<% else %>
<br /><br />
<div class="marquee">
  <p>現在準備中です。プレイ開始まで少々お待ちください。</p>
</div>
<% end %>

app/views/client/index.html.erb
<script type="text/javascript">
$(function(){
	$("#wakarimi-btn").click(function(){
	    $.ajax({
	      url: '/client/post_cheer',
	      type: 'GET',
	      success: function(json){
	      }
	    });
	});
});
</script>

<div id="client_contents">

	<nav class="navbar navbar-default" role="navigation">
		<div class="container">
			<div class="row">
				<div class="container-fluid">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
						<div class="col-xs-6 col-md-3">
							<img width="115px" height="65px" src="/assets/img/gachi-logo.png">
						</div>
						<div class="col-xs-6 col-md-3" height="100px">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
					</div>
				</div>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<br>
				<% users = User.all %>
				<% player = Player.now_playing_player %>
				<%= session[:user_name] %> さん！
				<br>
				ようこそガチ恋ガーデンへ！
				<br>
				<hr>
				現在参加中のオタク：
				<br>
				<% users.each_with_index do |user, idx| %>
				<% if users.size != idx + 1 %>
				<%= user.name %>、
				<% else %>
				<%= user.name %>
				<% end %>
				<% end %>
				<hr>
				<a href="/timetable.jpg" target="_blank">タイムテーブル</a>
				<hr>
				<a href="/flyer.jpg" target="_blank">フライヤー</a>
				<hr>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>

	<div class="container main">
		<div class="row">
			<div class="col-xs-12 centered">
				<img id="sorena" width="200px" height="200px" src="/assets/img/sore.png" class="img-responsive center-block">
			</div><!-- /col-lg-8 -->
		</div><!-- /row -->
	</div>
	<!-- /container -->

	<div class="container btn-area">
		<div class="row">
			<div class="col-xs-12 centered">
				<h2>wakaru!</h2>
			</div><!-- /col-lg-8 -->
		</div>
		<div class="row">
			<div class="col-xs-12 centered">
				<div class="button__holder">
					<button type="button" id="wakarimi-btn" class="wakarimi-btn ripple">
						♡
					</button>
				</div>
			</div><!-- /col-lg-8 -->
		</div><!-- /row -->
	</div>
</div>

<script src="/assets/js/touchpoint.js"></script>
</div>

app/views/client/user_login.html.erb
<div class="container head">
	<div class="row">
		<div class="col-xs-12 centered">
			<div class="logo">
				<img width="512px" height="288px" src="/assets/img/gachi-logo.png" class="img-responsive center-block">
	    	</div>
		</div><!-- /col-lg-8 -->
	</div><!-- /row -->
</div>

<%= form_tag(client_user_create_path) do %>
	<div class="container">
		<div class="row">
			<div class="col-xs-12 centered">
				<img width="344px" height="135px" src="/assets/img/wakarimi-logo.png" class="img-responsive center-block">
			</div>
			<div class="form-input-area">
				<div class="col-xs-12 centered">
					<div class="form-group">
						<input type="text" name="user_name" class="form-control" placeholder="オタク名">
					</div>
				</div><!-- /col-lg-8 -->
			</div>
		</div><!-- /row -->
		<div class="row">
			<div class="col-xs-12 centered">
				<div class="form-group">
					<input class="btn btn-info btn-lg" type="submit" value="登録"/>
				</div>
			</div><!-- /col-lg-8 -->
		</div><!-- /row -->
	</div> <!-- /container -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheerCounter</title>
    <%= csrf_meta_tags %>
<link rel="stylesheet" type="text/css" href="animate.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

 </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/client_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheerCounter</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="/assets/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/assets/css/client/login.css" rel="stylesheet">
    <link href="/assets/css/client/main.css" rel="stylesheet">
    <link href="/assets/css/client/countdown.css" rel="stylesheet">
    <link href="/assets/css/animate.css" rel="stylesheet">
    <link href="/assets/css/font-awesome.min.css" rel="stylesheet">
    <link href="/assets/css/bootstrap_custom.css" rel="stylesheet">
    <link href="/assets/css/bootstrap.offcanvas.css" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="/assets/js/chart.js"></script>
    <script src="/assets/js/bootstrap.offcanvas.js"></script>
 </head>

  <body>
    <%= yield %>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/assets/js/bootstrap.js"></script>
  </body>
</html>

app/views/layouts/master_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheerCounter</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="/assets/css/bootstrap4.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/assets/css/master/master.css" rel="stylesheet">
    <link href="/assets/css/animate.css" rel="stylesheet">
    <link href="/assets/css/font-awesome.min.css" rel="stylesheet">
    <link href="/assets/css/bootstrap_custom.css" rel="stylesheet">
    <link href="/assets/css/bootstrap.offcanvas.css" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="/assets/js/chart.js"></script>
    <script src="/assets/js/bootstrap.offcanvas.js"></script>

 </head>

  <body>
    <%= yield %>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/assets/js/bootstrap.js"></script>
  </body>
</html>

app/views/master/_count.html.erb
<%= @cheers.count %>

app/views/master/index.html.erb
<script type="text/javascript">

$(function(){
var count = 1;

function get_status(){
    $.ajax({
      url: '/master/get_status',
      type: 'GET',
      success: function(json){
        if(json.status == "stanby"){
          window.location.href = "/master/stanby";
        }
      }
    });
}

function ajax_function(){
  
    var deferred = new $.Deferred();
    var elm = document.getElementById("meter_status");
    
    $.ajax({
        url: '/master/get_cheers',
        type: 'GET',
        success: function(json){
          var step_status=json.step_status;
          var meter_status = elm.getAttribute('data-meter-status');
          var counter = json.counter;
          if(step_status == "1"){
            elm.setAttribute('data-meter-status', Number(meter_status) + 1);
          } else if(step_status == "-1"){
            elm.setAttribute('data-meter-status', Number(meter_status) - 1);
          };
          $("#counter").text(counter);
          deferred.resolve();
        }
    });
    
    return deferred;
}


function refresh(){
    get_status();
    var elm = document.getElementById("meter_status");
    
    var current_level;
    var current_level = $(".current_level").data("level");
    var meter_status = elm.getAttribute('data-meter-status');
    
    if(meter_status >= "3"){
      if($(".current_level").data("level") != $(".max").data("level")){
        $(".current_level").removeClass("current_level");
        current_level += 1;
        $(".level"+current_level).addClass("current_level");
        $(".level"+current_level).removeClass("blank");
        elm.setAttribute('data-meter-status', "2");
      } else {
        elm.setAttribute('data-meter-status', "2");
      }
    } else if(meter_status <= "0"){
      if($(".current_level").data("level") != $(".min").data("level")){
        $(".current_level").addClass("blank");
        $(".current_level").removeClass("current_level");
        current_level = current_level - 1;
        $(".level"+current_level).addClass("current_level");
        elm.setAttribute('data-meter-status', "2");
      } else {
        elm.setAttribute('data-meter-status', "2");
      }
    }
     
    var deferred = ajax_function();
    
    deferred.done(function(){
      setTimeout(refresh, 3000);
      count++;
    });
}
refresh();
});

</script>

<div class="container">

</div> <!-- /container -->
<div id="meter_status" class="meter_status" data-meter-status="2" hidden></div>

<% if @now_playing_player %>
<div class="container main">
  <div class="row align-items-center">
    <div class="col-md-6">
      <div class="meter level20 blank max" data-level="20"></div>
      <div class="meter level19 blank" data-level="19"></div>
      <div class="meter level18 blank" data-level="18"></div>
      <div class="meter level17 blank" data-level="17"></div>
      <div class="meter level16 blank" data-level="16"></div>
      <div class="meter level15 blank" data-level="15"></div>
      <div class="meter level14 blank" data-level="14"></div>
      <div class="meter level13 current_level" data-level="13"></div>
      <div class="meter level12" data-level="12"></div>
      <div class="meter level11" data-level="11"></div>
      <div class="meter level10" data-level="10"></div>
      <div class="meter level9" data-level="9"></div>
      <div class="meter level8" data-level="8"></div>
      <div class="meter level7" data-level="7"></div>
      <div class="meter level6" data-level="6"></div>
      <div class="meter level5" data-level="5"></div>
      <div class="meter level4 " data-level="4"></div>
      <div class="meter level3 min" data-level="3" hidden></div>
    </div>
    <div class="col-md-1 centered sub heart">♡　</div>
  	<div id="counter" class="col-md-5 count">
  	  <%= render :partial =>  "count" %>
  	</div><!-- /row -->
  </div>
</div> <!-- /container -->

<% else %>

<br /><br />
<div class="marquee">
  <p>現在準備中です。プレイ開始まで少々お待ちください。</p>
</div>
<% end %>

app/views/master/stanby.html.erb
<script type="text/javascript">
function get_status(){
    $.ajax({
      url: '/master/get_status',
      type: 'GET',
      success: function(json){
        if(json.status == "playing"){
          window.location.href = "/master/index";
        }
      }
    });
    setTimeout(get_status, 1000);
}

$(function(){
  get_status();

});
</script>


<br /><br />
<div class="marquee">
  <p>現在準備中です。プレイ開始まで少々お待ちください。</p>
</div>